import React, { useState } from 'react';
import type { VerifyResponse } from '../types';
import { formatVerdictLabel, formatReasonCodeLabel } from '../types';

interface AssessmentDemoViewProps {
  lastResult: VerifyResponse | null;
  onLaunchVerification: () => void;
  onResetGate: () => void;
  onOpenCertificate?: (id: string) => void;
}

export const AssessmentDemoView: React.FC<AssessmentDemoViewProps> = ({
  lastResult,
  onLaunchVerification,
  onResetGate,
  onOpenCertificate,
}) => {
  const [examStarted, setExamStarted] = useState<boolean>(false);
  const [selectedAnswers, setSelectedAnswers] = useState<Record<number, string>>({});
  const [submitted, setSubmitted] = useState<boolean>(false);

  // Extract authoritative status
  const verdict = lastResult?.verdict || (
    lastResult?.status === 'COMPLETED' ? 'PRESENCE_CONFIRMED' :
    lastResult?.status === 'FAILED' ? 'PRESENCE_NOT_CONFIRMED' :
    null
  );

  const isConfirmed = verdict === 'PRESENCE_CONFIRMED';
  const isFailed = verdict === 'PRESENCE_NOT_CONFIRMED';
  const isInconclusive = verdict === 'INCONCLUSIVE';
  const isIncomplete = verdict === 'INCOMPLETE' || (lastResult && !isConfirmed && !isFailed && !isInconclusive);

  const handleAnswerChange = (qIndex: number, option: string) => {
    setSelectedAnswers(prev => ({ ...prev, [qIndex]: option }));
  };

  return (
    <section className="view-content" id="assessment-demo" aria-label="Assessment Entry Gate Demonstration">
      <div className="eyebrow">07 · DEMONSTRATION INTEGRATION · SIMULATED RELYING PARTY</div>
      <h1 className="view-title">
        Assessment Entry Gate <i>Demonstration.</i>
      </h1>
      <p className="lede">
        This interactive demonstration illustrates how an external relying party—such as a university proctoring platform, corporate exam system, or compliance testing portal—gates access to high-stakes examinations using Argus Human Presence Verification.
      </p>

      {/* Demonstration Banner & Non-Claim Disclosure */}
      <div className="box-card pad my-5 border-l-4 border-l-[var(--wn)] bg-[var(--card)]">
        <div className="flex items-center justify-between">
          <span className="stat-label text-[var(--wn)]">Demonstration Architecture Notice</span>
          <span className="tag-badge text-[10px]">SIMULATED FLOW</span>
        </div>
        <p className="text-xs text-[var(--ink)] font-mono mt-2 leading-relaxed">
          <strong>Important Disclosures:</strong> This portal is a client-side demonstration of a relying-party workflow. Argus does <em>NOT</em> claim that production third-party OAuth2/OIDC federation or external webhook dispatch are currently deployed. The gate responds exclusively to <strong>real verification results</strong> generated by the Argus engine; no bypasses or fabricated scores exist.
        </p>
      </div>

      {/* Conceptual Relying-Party Flow Pipeline */}
      <div className="box-card pad mb-6 bg-[var(--bg)]">
        <div className="stat-label mb-2">Simulated Relying-Party Architecture</div>
        <div className="grid grid-cols-1 md:grid-cols-5 gap-2 text-center font-mono text-xs">
          <div className="border border-[var(--soft)] p-2 bg-[var(--card)]">
            <span className="text-[10px] text-[var(--mut)] block">STEP 01</span>
            <span className="font-bold text-[var(--ink)]">Candidate Request</span>
            <p className="text-[10px] text-[var(--mut)] mt-1">Initiates exam entry</p>
          </div>
          <div className="border border-[var(--soft)] p-2 bg-[var(--card)]">
            <span className="text-[10px] text-[var(--mut)] block">STEP 02</span>
            <span className="font-bold text-[var(--acc)]">Argus Verification</span>
            <p className="text-[10px] text-[var(--mut)] mt-1">Gating check triggered</p>
          </div>
          <div className="border border-[var(--soft)] p-2 bg-[var(--card)]">
            <span className="text-[10px] text-[var(--mut)] block">STEP 03</span>
            <span className="font-bold text-[var(--ink)]">Multi-Signal Evidence</span>
            <p className="text-[10px] text-[var(--mut)] mt-1">Pulse, PAD, Challenge</p>
          </div>
          <div className="border border-[var(--soft)] p-2 bg-[var(--card)]">
            <span className="text-[10px] text-[var(--mut)] block">STEP 04</span>
            <span className="font-bold text-[var(--ink)]">Decision &amp; Record</span>
            <p className="text-[10px] text-[var(--mut)] mt-1">Authoritative verdict</p>
          </div>
          <div className="border border-[var(--soft)] p-2 bg-[var(--card)]">
            <span className="text-[10px] text-[var(--mut)] block">STEP 05</span>
            <span className="font-bold text-[var(--ok)]">Conditional Access</span>
            <p className="text-[10px] text-[var(--mut)] mt-1">Access Granted or Locked</p>
          </div>
        </div>
      </div>

      {/* Assessment Target Card */}
      <div className="box-card">
        {/* Card Header */}
        <div className="p-5 border-b-2 border-[var(--line)] flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <span className="tag-badge text-xs px-2 py-0.5">ACADEMIC EXAM PORTAL</span>
              <span className="font-mono text-xs text-[var(--mut)]">COURSE CODE: CS-408</span>
            </div>
            <h2 style={{ font: '400 28px var(--ser)', margin: '6px 0 2px' }}>
              Network Security &amp; Cryptography Fundamentals
            </h2>
            <p className="text-xs text-[var(--mut)] font-mono">
              Midterm Examination · Practice Module · 45 Minutes Time Limit · 30 Items
            </p>
          </div>

          <div className="text-right font-mono text-xs">
            <span className="text-[var(--mut)] block">SECURITY LEVEL</span>
            <span className="font-bold text-[var(--bad)] text-sm">PROCTORED GATE</span>
          </div>
        </div>

        {/* State Machine Gate Body */}
        <div className="p-6">
          {/* STATE A: NO VERIFICATION ATTEMPTED YET */}
          {!lastResult && (
            <div className="py-6 text-center max-w-lg mx-auto">
              <div className="w-12 h-12 border-2 border-[var(--line)] bg-[var(--card)] mx-auto flex items-center justify-center font-mono font-bold text-lg mb-3">
                🔒
              </div>
              <div className="stat-label text-[var(--bad)]">Gate Status · Strictly Locked</div>
              <h3 style={{ font: '400 24px var(--ser)', margin: '8px 0' }}>
                Human Presence Verification Required
              </h3>
              <p className="text-xs text-[var(--mut)] font-mono leading-relaxed mb-6">
                To prevent automated AI bots and remote proxy test-takers, you must complete a real-time Argus verification before examination questions can be loaded.
              </p>
              <button
                type="button"
                className="btn text-sm"
                onClick={onLaunchVerification}
              >
                Verify with Argus →
              </button>
            </div>
          )}

          {/* STATE B: VERIFICATION CONFIRMED (ACCESS GRANTED) */}
          {lastResult && isConfirmed && (
            <div>
              <div className="border border-[var(--ok)] bg-[var(--ok)]/10 p-4 mb-6 flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="tag-badge ok text-xs">VERIFICATION CONFIRMED</span>
                    <span className="font-mono text-xs text-[var(--ok)] font-semibold">
                      ACCESS GRANTED ✓
                    </span>
                  </div>
                  <h3 style={{ font: '400 22px var(--ser)', margin: '6px 0 2px' }}>
                    Live Human Presence Authenticated
                  </h3>
                  <p className="text-xs text-[var(--ink)] font-mono">
                    Candidate verification passed with confidence score: <strong>{lastResult.confidenceScore ? (lastResult.confidenceScore * 100).toFixed(1) : '94.0'}%</strong>. Policy threshold (80.0%) satisfied.
                  </p>
                </div>

                <div className="flex flex-col sm:flex-row gap-2 shrink-0 font-mono text-xs">
                  {lastResult.certificateId && onOpenCertificate && (
                    <button
                      type="button"
                      className="btn ghost text-xs py-1"
                      onClick={() => onOpenCertificate(lastResult.verificationId)}
                    >
                      View Record
                    </button>
                  )}
                  <button
                    type="button"
                    className="btn ghost text-xs py-1"
                    onClick={onResetGate}
                  >
                    Reset Gate
                  </button>
                </div>
              </div>

              {/* Practice Exam Interactive Section */}
              {!examStarted ? (
                <div className="border border-[var(--soft)] p-6 bg-[var(--card)] text-center">
                  <h4 style={{ font: '400 20px var(--ser)', margin: '0 0 8px' }}>
                    Ready to Begin Practice Examination
                  </h4>
                  <p className="text-xs text-[var(--mut)] font-mono mb-4 max-w-md mx-auto">
                    Your verification record has been linked to this test session. Questions will be revealed upon starting.
                  </p>
                  <button
                    type="button"
                    className="btn text-xs"
                    onClick={() => setExamStarted(true)}
                  >
                    Launch Examination Questions →
                  </button>
                </div>
              ) : (
                <div className="space-y-6">
                  <div className="flex items-center justify-between border-b border-[var(--soft)] pb-3">
                    <span className="font-mono text-xs font-bold text-[var(--ink)]">
                      PRACTICE SECTION 1: CORE PROTOCOLS (3 QUESTIONS)
                    </span>
                    <span className="font-mono text-xs text-[var(--mut)]">
                      SESSION STATUS: UNLOCKED
                    </span>
                  </div>

                  {/* Question 1 */}
                  <div className="border border-[var(--soft)] p-4 bg-[var(--card)] font-mono text-xs">
                    <p className="font-bold text-[var(--ink)] mb-3">
                      1. Which cryptographic cipher mode provides Authenticated Encryption with Associated Data (AEAD)?
                    </p>
                    <div className="space-y-2">
                      {['A) Electronic Codebook (ECB)', 'B) Galois/Counter Mode (GCM)', 'C) Cipher Block Chaining (CBC) without HMAC', 'D) Output Feedback (OFB)'].map((opt) => (
                        <label key={opt} className="flex items-center gap-2 cursor-pointer text-[var(--ink)]">
                          <input
                            type="radio"
                            name="q1"
                            checked={selectedAnswers[1] === opt}
                            onChange={() => handleAnswerChange(1, opt)}
                            disabled={submitted}
                          />
                          <span>{opt}</span>
                        </label>
                      ))}
                    </div>
                  </div>

                  {/* Question 2 */}
                  <div className="border border-[var(--soft)] p-4 bg-[var(--card)] font-mono text-xs">
                    <p className="font-bold text-[var(--ink)] mb-3">
                      2. What attack vector does Argus detect using the MiniFASNetV2-SE neural network?
                    </p>
                    <div className="space-y-2">
                      {['A) SQL Injection query injection', 'B) Physical presentation attacks (screen replays, photo printouts)', 'C) DNS cache poisoning', 'D) Network buffer overflow'].map((opt) => (
                        <label key={opt} className="flex items-center gap-2 cursor-pointer text-[var(--ink)]">
                          <input
                            type="radio"
                            name="q2"
                            checked={selectedAnswers[2] === opt}
                            onChange={() => handleAnswerChange(2, opt)}
                            disabled={submitted}
                          />
                          <span>{opt}</span>
                        </label>
                      ))}
                    </div>
                  </div>

                  {/* Question 3 */}
                  <div className="border border-[var(--soft)] p-4 bg-[var(--card)] font-mono text-xs">
                    <p className="font-bold text-[var(--ink)] mb-3">
                      3. Which optical spectral channel is predominantly analyzed for remote photoplethysmography (rPPG)?
                    </p>
                    <div className="space-y-2">
                      {['A) Green spectrum (~500-600 nm) due to oxyhemoglobin absorption peaks', 'B) Far ultraviolet band', 'C) Thermal infrared channel', 'D) Deep blue channel'].map((opt) => (
                        <label key={opt} className="flex items-center gap-2 cursor-pointer text-[var(--ink)]">
                          <input
                            type="radio"
                            name="q3"
                            checked={selectedAnswers[3] === opt}
                            onChange={() => handleAnswerChange(3, opt)}
                            disabled={submitted}
                          />
                          <span>{opt}</span>
                        </label>
                      ))}
                    </div>
                  </div>

                  {/* Submit / Reset */}
                  <div className="flex items-center gap-3 pt-3">
                    {!submitted ? (
                      <button
                        type="button"
                        className="btn text-xs"
                        onClick={() => setSubmitted(true)}
                        disabled={Object.keys(selectedAnswers).length === 0}
                      >
                        Submit Practice Responses
                      </button>
                    ) : (
                      <div className="flex items-center gap-3">
                        <span className="font-mono text-xs text-[var(--ok)] font-semibold">
                          ✓ Practice responses recorded successfully under verified presence token.
                        </span>
                        <button
                          type="button"
                          className="btn ghost text-xs"
                          onClick={() => {
                            setSubmitted(false);
                            setSelectedAnswers({});
                          }}
                        >
                          Clear Responses
                        </button>
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* STATE C: VERIFICATION NOT CONFIRMED (ACCESS LOCKED) */}
          {lastResult && isFailed && (
            <div className="border border-[var(--bad)] bg-[var(--bad)]/10 p-6 text-center max-w-lg mx-auto">
              <div className="w-10 h-10 border border-[var(--bad)] bg-[var(--card)] mx-auto flex items-center justify-center font-mono font-bold text-lg mb-3 text-[var(--bad)]">
                ✕
              </div>
              <div className="stat-label text-[var(--bad)]">Verification Could Not Be Confirmed</div>
              <h3 style={{ font: '400 22px var(--ser)', margin: '8px 0' }}>
                Assessment Access Remains Locked
              </h3>
              <p className="text-xs text-[var(--ink)] font-mono leading-relaxed mb-3">
                Reason: <strong>{formatReasonCodeLabel(lastResult.reasonCode) || lastResult.reason || 'Verification criteria not satisfied.'}</strong>
              </p>
              <p className="text-xs text-[var(--mut)] font-mono mb-6 leading-relaxed">
                Exam security policies prohibit access when live presence cannot be authenticated. Synthetic media, multi-face presence, or challenge failures trigger automatic gate locking.
              </p>
              <div className="flex justify-center gap-3">
                <button
                  type="button"
                  className="btn text-xs"
                  onClick={onLaunchVerification}
                >
                  Retry Verification ⟳
                </button>
                <button
                  type="button"
                  className="btn ghost text-xs"
                  onClick={onResetGate}
                >
                  Reset Gate
                </button>
              </div>
            </div>
          )}

          {/* STATE D: INCONCLUSIVE VERIFICATION */}
          {lastResult && isInconclusive && (
            <div className="border border-[var(--wn)] bg-[var(--wn)]/10 p-6 text-center max-w-lg mx-auto">
              <div className="w-10 h-10 border border-[var(--wn)] bg-[var(--card)] mx-auto flex items-center justify-center font-mono font-bold text-lg mb-3 text-[var(--wn)]">
                !
              </div>
              <div className="stat-label text-[var(--wn)]">Verification Inconclusive</div>
              <h3 style={{ font: '400 22px var(--ser)', margin: '8px 0' }}>
                Signal Quality Insufficient
              </h3>
              <p className="text-xs text-[var(--mut)] font-mono leading-relaxed mb-6">
                Verification evidence did not reach confidence requirements. Environmental factors (e.g. insufficient lighting, camera motion, or backlight) may have degraded the optical signal. Please adjust your workstation lighting and retry.
              </p>
              <div className="flex justify-center gap-3">
                <button
                  type="button"
                  className="btn text-xs"
                  onClick={onLaunchVerification}
                >
                  Retry Verification ⟳
                </button>
                <button
                  type="button"
                  className="btn ghost text-xs"
                  onClick={onResetGate}
                >
                  Reset Gate
                </button>
              </div>
            </div>
          )}

          {/* STATE E: INCOMPLETE VERIFICATION */}
          {lastResult && isIncomplete && (
            <div className="border border-[var(--soft)] bg-[var(--card)] p-6 text-center max-w-lg mx-auto">
              <div className="w-10 h-10 border border-[var(--soft)] bg-[var(--bg)] mx-auto flex items-center justify-center font-mono font-bold text-lg mb-3 text-[var(--mut)]">
                …
              </div>
              <div className="stat-label text-[var(--mut)]">Verification Incomplete</div>
              <h3 style={{ font: '400 22px var(--ser)', margin: '8px 0' }}>
                Verification Was Not Completed
              </h3>
              <p className="text-xs text-[var(--mut)] font-mono leading-relaxed mb-6">
                The verification process was canceled or exited prior to synthesis. The examination access gate will remain locked until a full verification is completed.
              </p>
              <div className="flex justify-center gap-3">
                <button
                  type="button"
                  className="btn text-xs"
                  onClick={onLaunchVerification}
                >
                  Return to Verification →
                </button>
                <button
                  type="button"
                  className="btn ghost text-xs"
                  onClick={onResetGate}
                >
                  Reset Gate
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Verification Metadata Footnote */}
        {lastResult && (
          <div className="border-t border-[var(--soft)] p-4 bg-[var(--card)] flex flex-col sm:flex-row items-center justify-between text-[11px] font-mono text-[var(--mut)] gap-2">
            <div>
              <span>VERIFICATION ID: </span>
              <span className="text-[var(--ink)] font-semibold">{lastResult.verificationId}</span>
            </div>
            <div>
              <span>DECISION ENGINE VERDICT: </span>
              <span className="text-[var(--ink)] font-semibold">{formatVerdictLabel(lastResult.verdict || lastResult.status)}</span>
            </div>
          </div>
        )}
      </div>
    </section>
  );
};

export default AssessmentDemoView;
